### ISSUE TITLE
LSBench Data Generator Not Found

### ISSUE THREAD

**Issue by zzxx-husky** [cqels/LSBench#1]
Hi, I wonder whether this repo will provide the source code of the LSBench data generator (for now or in the near future)? What I can find for the data generator is [a google code archive](https://code.google.com/archive/p/lsbench/wikis/benchmark_usecase.wiki). However, the link in that webpage to download the source code is invalid now. Do you know where I can get the source code of the data generator?

By the way, the following paper also uses the LSBench for evaluation:
+ Sub-millisecond Stateful Stream Querying over Fast-evolving Linked Data, SOSP' 17.

**Comment by danhlephuoc** [comment]
Hi,

I've add sourced code to the subdirectory ./main/, have a look.

**Comment by zzxx-husky** [comment]
Looks good! Thank you very much!
